### ISSUE TITLE
Add support for wildcards in project files

### ISSUE THREAD

**Issue by chrischu** [chrischu/SolutionInspector#2]
Probably just by creating a special IProjectItem derived class (that has a method/property that can be queried to get all affected files) and using it when a project item includes a wildcard.

**Comment by ulrichb** [comment]
Is `Exclude` also supported?
e.g. `<Compile Include="**\*.cs" Exclude="obj\**" />`

And multiple patterns?
e.g. `<Compile Include="A\**\*.cs;B\*.cs" Exclude="A\Sub\**;B\x.cs" />`

**Comment by chrischu** [comment]
Good point! In the current implementation Excludes are not handled correctly, but I'll change that before the 0.2.0 release :).

**Comment by ulrichb** [comment]
Thx.

**Comment by chrischu** [comment]
Ok as it turns out, MSBuild already handles wildcards correctly (and since I use MSBuild to obtain the project items so does SolutionInspector), I just improved the information contained in the SolutionInspector MSBuild object model to make inclusions/exclusions by wildcards visible.

**Comment by ulrichb** [comment]
Great. Thanks.
